### ISSUE TITLE
Vuetify/Material Dashboard for Vue3

### ISSUE THREAD

**Issue by sarogersz** [creativetimofficial/vue-material-dashboard-2#8]
My Vue2 app was created based on Material Dashboard Pro 2 with Vuetify.  I want to do a major overhaul and migrate it to Vue3.  I am studying what this entails.

My inclination is to start fresh on Vue3 and the latest Vuetify (which is due to support Vue3 this month).

Do you have Material Dashboard for Vuetify/Vue3 yet?

**Comment by sajadevo** [comment]
**Hi @sarogersz**

Thanks for working with our product, the current product is based on VueJS 3 but unfortunately at the moment we don't have any template based on Vuetify/Vue 3.

**Note: To get the latest updates and supports for the products and other related things to Creative Tim please join our [Discord Community](https://discord.gg/7xzMRsRebr).**

**All the best,
Sajad 
React Developer @ [Creative-Tim.com](http://creative-tim.com/)**

**Comment by sarogersz** [comment]
Please clarify what you are saying.  You seem to be contradicting yourself.  The only “product” we are discussing is a template.

Thanks, Stephen

**Comment by sarogersz** [comment]
Never mind – I missed the word Vuetify.  I get it and thanks for the reply.

From: Stephen Rogers
Sent: Thursday, May 12, 2022 9:46 AM
To: creativetimofficial/vue-material-dashboard-2 ***@***.***>; creativetimofficial/vue-material-dashboard-2 ***@***.***>
Cc: Mention ***@***.***>
Subject: RE: [creativetimofficial/vue-material-dashboard-2] Vuetify/Material Dashboard for Vue3 (Issue #8)

Please clarify what you are saying.  You seem to be contradicting yourself.  The only “product” we are discussing is a template.

Thanks, Stephen
